from enum import Enum


class RunParamKeys(str, Enum):
    FILE_NAME_MIDDLE_OVERRIDE = 'FILE_NAME_MIDDLE_OVERRIDE'
    RUN_NUMBER_TO_USE = 'RUN_NUMBER_TO_USE'
    DIFF_RESET_LOAD_DIRECTION = 'DIFF_RESET_LOAD_DIRECTION'
    PIPELINE_FINISHED = 'PIPELINE_FINISHED'
    PROCESS_TIME_PER_COMPRESSOR = 'PROCESS_TIME_PER_COMPRESSOR'
    DONT_SAVE_PROCESSING_TIME = 'DONT_SAVE_PROCESSING_TIME '
    TRAINING_DATA = 'TRAINING_DATA'
    LOSS = 'LOSS'
